// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocietyManagementShowcase.Common;

#nullable disable

namespace SocietyManagementShowcase.Migrations
{
    [DbContext(typeof(EfCoreDbContext))]
    [Migration("20250707074205_GymDateOnlyToDateTime")]
    partial class GymDateOnlyToDateTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocietyManagementShowcase.Models.CommonAmenities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LastMaintenanceCheck")
                        .HasColumnType("date");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SocietyId");

                    b.ToTable("CommonAmenities");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.ElectricityGenerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BackupGeneratorEngineId")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BackupGeneratorEngineId");

                    b.HasIndex("WingId")
                        .IsUnique();

                    b.ToTable("ElectricityGenerator");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Elevator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WingId");

                    b.ToTable("Elevator");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FuelLevel")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LastMaintenanceCheck")
                        .HasColumnType("date");

                    b.Property<int>("OilLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Engine");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.FireFightingSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FireId")
                        .HasColumnType("int");

                    b.Property<int>("FireSystemEngineId")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FireId");

                    b.HasIndex("FireSystemEngineId");

                    b.ToTable("FireFightingSystem");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Flat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AreaSqFt")
                        .HasColumnType("real");

                    b.Property<string>("FlatNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MaintenanceCharge")
                        .HasColumnType("real");

                    b.Property<int>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WingId");

                    b.ToTable("Flat");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastMaintenanceCheck")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Gym");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.IssueTicketLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SocietyId");

                    b.HasIndex("WingId");

                    b.ToTable("IssueTicketLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommonAmenitiesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EngineId")
                        .HasColumnType("int");

                    b.Property<int?>("GymId")
                        .HasColumnType("int");

                    b.Property<string>("MaintenaceCheckedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintenaceDoneByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SwimmingPoolId")
                        .HasColumnType("int");

                    b.Property<int?>("WaterFiltrationSystemId")
                        .HasColumnType("int");

                    b.Property<int?>("WaterTankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommonAmenitiesId");

                    b.HasIndex("EngineId");

                    b.HasIndex("GymId");

                    b.HasIndex("SwimmingPoolId");

                    b.HasIndex("WaterFiltrationSystemId");

                    b.HasIndex("WaterTankId");

                    b.ToTable("MaintenanceLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Contact")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FlatId")
                        .HasColumnType("int");

                    b.Property<string>("FlatNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlatId");

                    b.HasIndex("SocietyId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Society", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FireSystemId")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("IndoorGymId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfWings")
                        .HasColumnType("int");

                    b.Property<double>("TotalFlatAreaSociety")
                        .HasColumnType("float");

                    b.Property<double>("TotalMaintenanceChargeSociety")
                        .HasColumnType("float");

                    b.Property<int>("WaterFilterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FireSystemId");

                    b.HasIndex("IndoorGymId");

                    b.HasIndex("WaterFilterId");

                    b.ToTable("Society");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.SwimmingPool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LastMaintenanceCheck")
                        .HasColumnType("date");

                    b.Property<int>("PoolType")
                        .HasColumnType("int");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SocietyId");

                    b.ToTable("SwimmingPool");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.VisitorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int");

                    b.Property<string>("Wing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SocietyId");

                    b.HasIndex("WingId");

                    b.ToTable("VisitorLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.WaterFiltrationSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LastMaintenanceCheck")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("WaterFiltrationSystem");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.WaterTank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LastMaintenanceCheck")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WaterLevel")
                        .HasColumnType("int");

                    b.Property<int>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WingId");

                    b.ToTable("WaterTank");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Wing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ElectricMeterBill")
                        .HasColumnType("float");

                    b.Property<double>("ElectricMeterReading")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("NoticeBoard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int");

                    b.Property<int>("SubManagerId")
                        .HasColumnType("int");

                    b.Property<double>("TotalFlatAreaWing")
                        .HasColumnType("float");

                    b.Property<double>("TotalMaintenanceChargeWing")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SocietyId");

                    b.HasIndex("SubManagerId");

                    b.ToTable("Wing");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.CommonAmenities", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Society", null)
                        .WithMany("CommonAmenities")
                        .HasForeignKey("SocietyId");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.ElectricityGenerator", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Engine", "BackupGeneratorEngine")
                        .WithMany()
                        .HasForeignKey("BackupGeneratorEngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocietyManagementShowcase.Models.Wing", "Wing")
                        .WithOne("BackupGenerator")
                        .HasForeignKey("SocietyManagementShowcase.Models.ElectricityGenerator", "WingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackupGeneratorEngine");

                    b.Navigation("Wing");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Elevator", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Wing", "Wing")
                        .WithMany("Elevators")
                        .HasForeignKey("WingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wing");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.FireFightingSystem", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.WaterTank", "Fire")
                        .WithMany()
                        .HasForeignKey("FireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocietyManagementShowcase.Models.Engine", "FireSystemEngine")
                        .WithMany()
                        .HasForeignKey("FireSystemEngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fire");

                    b.Navigation("FireSystemEngine");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Flat", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Wing", "Wing")
                        .WithMany("FlatList")
                        .HasForeignKey("WingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wing");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.IssueTicketLog", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Person", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocietyManagementShowcase.Models.Society", null)
                        .WithMany("IssueTicketSociety")
                        .HasForeignKey("SocietyId");

                    b.HasOne("SocietyManagementShowcase.Models.Wing", null)
                        .WithMany("IssueTicketWing")
                        .HasForeignKey("WingId");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.MaintenanceLog", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.CommonAmenities", null)
                        .WithMany("CommonAmenitiesMaintenaceLog")
                        .HasForeignKey("CommonAmenitiesId");

                    b.HasOne("SocietyManagementShowcase.Models.Engine", null)
                        .WithMany("EngineMaintenaceLog")
                        .HasForeignKey("EngineId");

                    b.HasOne("SocietyManagementShowcase.Models.Gym", null)
                        .WithMany("GymMaintenaceLog")
                        .HasForeignKey("GymId");

                    b.HasOne("SocietyManagementShowcase.Models.SwimmingPool", null)
                        .WithMany("SwimmingPoolMaintenaceLog")
                        .HasForeignKey("SwimmingPoolId");

                    b.HasOne("SocietyManagementShowcase.Models.WaterFiltrationSystem", null)
                        .WithMany("WaterFiltrationSystemMaintenaceLog")
                        .HasForeignKey("WaterFiltrationSystemId");

                    b.HasOne("SocietyManagementShowcase.Models.WaterTank", null)
                        .WithMany("WaterTankMaintenaceLog")
                        .HasForeignKey("WaterTankId");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Person", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Flat", null)
                        .WithMany("Residents")
                        .HasForeignKey("FlatId");

                    b.HasOne("SocietyManagementShowcase.Models.Society", null)
                        .WithMany("Staff")
                        .HasForeignKey("SocietyId");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Society", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.FireFightingSystem", "FireSystem")
                        .WithMany()
                        .HasForeignKey("FireSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocietyManagementShowcase.Models.Gym", "IndoorGym")
                        .WithMany()
                        .HasForeignKey("IndoorGymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocietyManagementShowcase.Models.WaterFiltrationSystem", "WaterFilter")
                        .WithMany()
                        .HasForeignKey("WaterFilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FireSystem");

                    b.Navigation("IndoorGym");

                    b.Navigation("WaterFilter");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.SwimmingPool", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Society", null)
                        .WithMany("SwimmingPools")
                        .HasForeignKey("SocietyId");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.VisitorLog", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Society", null)
                        .WithMany("LogOfVisitors")
                        .HasForeignKey("SocietyId");

                    b.HasOne("SocietyManagementShowcase.Models.Wing", null)
                        .WithMany("LogOfVisitors")
                        .HasForeignKey("WingId");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.WaterTank", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Wing", "Wing")
                        .WithMany("WaterTanks")
                        .HasForeignKey("WingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wing");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Wing", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Society", null)
                        .WithMany("Wing")
                        .HasForeignKey("SocietyId");

                    b.HasOne("SocietyManagementShowcase.Models.Person", "SubManager")
                        .WithMany()
                        .HasForeignKey("SubManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubManager");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.CommonAmenities", b =>
                {
                    b.Navigation("CommonAmenitiesMaintenaceLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Engine", b =>
                {
                    b.Navigation("EngineMaintenaceLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Flat", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Gym", b =>
                {
                    b.Navigation("GymMaintenaceLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Society", b =>
                {
                    b.Navigation("CommonAmenities");

                    b.Navigation("IssueTicketSociety");

                    b.Navigation("LogOfVisitors");

                    b.Navigation("Staff");

                    b.Navigation("SwimmingPools");

                    b.Navigation("Wing");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.SwimmingPool", b =>
                {
                    b.Navigation("SwimmingPoolMaintenaceLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.WaterFiltrationSystem", b =>
                {
                    b.Navigation("WaterFiltrationSystemMaintenaceLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.WaterTank", b =>
                {
                    b.Navigation("WaterTankMaintenaceLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Wing", b =>
                {
                    b.Navigation("BackupGenerator")
                        .IsRequired();

                    b.Navigation("Elevators");

                    b.Navigation("FlatList");

                    b.Navigation("IssueTicketWing");

                    b.Navigation("LogOfVisitors");

                    b.Navigation("WaterTanks");
                });
#pragma warning restore 612, 618
        }
    }
}
