// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocietyManagementShowcase.Common;

#nullable disable

namespace SocietyManagementShowcase.Migrations
{
    [DbContext(typeof(EfCoreDbContext))]
    [Migration("20250703111836_PersonFlat")]
    partial class PersonFlat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocietyManagementShowcase.Models.ElectricityGenerator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BackupGeneratorEngineId")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BackupGeneratorEngineId");

                    b.HasIndex("WingId")
                        .IsUnique();

                    b.ToTable("ElectricityGenerator");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Elevator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WingId");

                    b.ToTable("Elevator");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Engine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FuelLevel")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LastMaintenanceCheck")
                        .HasColumnType("date");

                    b.Property<int>("OilLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Engine");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Flat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AreaSqFt")
                        .HasColumnType("real");

                    b.Property<string>("FlatNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MaintenanceCharge")
                        .HasColumnType("real");

                    b.Property<int>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WingId");

                    b.ToTable("Flat");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.IssueTicketLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("WingId");

                    b.ToTable("IssueTicketLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.MaintenanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EngineId")
                        .HasColumnType("int");

                    b.Property<string>("MaintenaceCheckedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaintenaceDoneByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WaterTankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EngineId");

                    b.HasIndex("WaterTankId");

                    b.ToTable("MaintenanceLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Contact")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FlatId")
                        .HasColumnType("int");

                    b.Property<string>("FlatNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FlatId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.VisitorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wing")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WingId");

                    b.ToTable("VisitorLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.WaterTank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<DateOnly>("LastMaintenanceCheck")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("WaterLevel")
                        .HasColumnType("int");

                    b.Property<int>("WingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WingId");

                    b.ToTable("WaterTank");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Wing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ElectricMeterBill")
                        .HasColumnType("float");

                    b.Property<double>("ElectricMeterReading")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("NoticeBoard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubManagerId")
                        .HasColumnType("int");

                    b.Property<double>("TotalFlatAreaWing")
                        .HasColumnType("float");

                    b.Property<double>("TotalMaintenanceChargeWing")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SubManagerId");

                    b.ToTable("Wing");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.ElectricityGenerator", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Engine", "BackupGeneratorEngine")
                        .WithMany()
                        .HasForeignKey("BackupGeneratorEngineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocietyManagementShowcase.Models.Wing", "Wing")
                        .WithOne("BackupGenerator")
                        .HasForeignKey("SocietyManagementShowcase.Models.ElectricityGenerator", "WingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackupGeneratorEngine");

                    b.Navigation("Wing");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Elevator", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Wing", "Wing")
                        .WithMany("Elevators")
                        .HasForeignKey("WingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wing");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Flat", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Wing", "Wing")
                        .WithMany("FlatList")
                        .HasForeignKey("WingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wing");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.IssueTicketLog", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Person", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SocietyManagementShowcase.Models.Wing", null)
                        .WithMany("IssueTicketWing")
                        .HasForeignKey("WingId");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.MaintenanceLog", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Engine", null)
                        .WithMany("EngineMaintenaceLog")
                        .HasForeignKey("EngineId");

                    b.HasOne("SocietyManagementShowcase.Models.WaterTank", null)
                        .WithMany("WaterTankMaintenaceLog")
                        .HasForeignKey("WaterTankId");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Person", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Flat", null)
                        .WithMany("Residents")
                        .HasForeignKey("FlatId");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.VisitorLog", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Wing", null)
                        .WithMany("LogOfVisitors")
                        .HasForeignKey("WingId");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.WaterTank", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Wing", "Wing")
                        .WithMany("WaterTanks")
                        .HasForeignKey("WingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wing");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Wing", b =>
                {
                    b.HasOne("SocietyManagementShowcase.Models.Person", "SubManager")
                        .WithMany()
                        .HasForeignKey("SubManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubManager");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Engine", b =>
                {
                    b.Navigation("EngineMaintenaceLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Flat", b =>
                {
                    b.Navigation("Residents");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.WaterTank", b =>
                {
                    b.Navigation("WaterTankMaintenaceLog");
                });

            modelBuilder.Entity("SocietyManagementShowcase.Models.Wing", b =>
                {
                    b.Navigation("BackupGenerator")
                        .IsRequired();

                    b.Navigation("Elevators");

                    b.Navigation("FlatList");

                    b.Navigation("IssueTicketWing");

                    b.Navigation("LogOfVisitors");

                    b.Navigation("WaterTanks");
                });
#pragma warning restore 612, 618
        }
    }
}
